services:
    Subugoe\ResolverBundle\Service\ResolverService:
      autoconfigure: true
      autowire: true
      calls:
        - method: setParameters
          arguments:
            - "%service%"
            - "%servicehome%"
